- name: apt-update
  apt:
    update_cache: yes

- name: install-java
  apt:
    name: openjdk-11-jdk
    state: present

- name: Download-jenkins-key
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
    mode: '0644'

- name: Add a line to a file if the file does not exist, without passing regexp
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/jenkins.list
    line: 'deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/'
    create: yes

- name: apt-update
  apt:
    update_cache: yes

- name: install-jenkins
  apt:
    name: jenkins
    state: present

- name: Start service httpd, if not started
  ansible.builtin.service:
    name: jenkins
    state: started
