# install docker 
- name: Download Docker GPG key
  get_url:
    url: "{{ DockerDownloadKey }}"
    dest: "{{ DockerDownloadKeyDist }}"
    

- name: find if docker-archive-keyring.gpg if exist 
  stat:
    path:  "{{ dockerArchiveKeyringPath }}"
  register: key_exists

- name: Import Docker GPG key
  shell: cat /tmp/docker.gpg | sudo gpg  --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg 
  when: key_exists.stat.exists == false

- name: Get architecture
  shell: dpkg --print-architecture
  register: dpkg_architecture

- name: Add Docker repository to apt sources
  lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: 'deb [arch={{ dpkg_architecture.stdout }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable'
    create: true

- name: update apt 
  apt:
    update_cache: yes

- name: install docker packages 
  apt:
    name: docker-ce,docker-ce-cli,containerd.io
    state: present

- name: Change file ownership
  file:
    path:  /var/run/docker.sock
    owner: ubuntu
    group: ubuntu
    mode: '0666'